export const resturants = [
    {
        name: "Chinese work",
        rating: "3.9",
        deliveryTime: "30-35",
        cuisines: "Chinese, Asian, Tibetan",
        location: "VVip Style mall",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fa4944f0cfdcbca2bec1f3ab8e3db3f7",
    },
    {
        name: "Pizza Hut",
        rating: "4.4",
        deliveryTime: "35-40",
        cuisines: "Pizza",
        location: "Rajnagar",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/12/5/dc74a4b7-8d63-4eb7-91c9-048973c2cc99_1003414.jpg",
    },
    {
        name: "Champaran Handi",
        rating: "3.9",
        deliveryTime: "50-55",
        cuisines: "North Indian",
        location: "Nagpur Road",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/xph0vf5pvbxjf8xchwjk",
    },
    {
        name: "Magic Momo",
        rating: "4.4",
        deliveryTime: "35-40",
        cuisines: "Momo, Chinese",
        location: "Parsia Road",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/dh0qsuqritnmbncwrni3",
    },
    {
        name: "Chaska Cafe",
        rating: "3.8",
        deliveryTime: "50-55",
        cuisines: "Cafe, Italian, Chinese",
        location: "Chhindwara city",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/uxgpy3bwmc5rsojmtw43",
    },
    {
        name: "Roof 5",
        rating: "4.4",
        deliveryTime: "35-40",
        cuisines: "Indian",
        location: "Chhindwara Locality",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/glepanv4xjfnhsbieam1",
    },
    {
        name: "Om ki Bakery",
        rating: "3.9",
        deliveryTime: "50-55",
        cuisines: "Bakery",
        location: "Chhindwara city",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/tgh1teo4lkj5kuk7fkmo",
    },
    {
        name: "Famous dum biryani",
        rating: "4.4",
        deliveryTime: "35-40",
        cuisines: "Biryani, North Indian",
        location: "Chhindwara city",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/f594f4f63d3e00e93203f02d40e38d24",
    },
    {
        name: "Kathi Junction",
        rating: "3.9",
        deliveryTime: "50-55",
        cuisines: "Rolls, Burger, Pizza, Fast Food",
        location: "Prasia Road",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/nigqvxgzvyxtfjuqasgg",
    },
    {
        name: "Bengla Punjab",
        rating: "4.4",
        deliveryTime: "35-40",
        cuisines: "North Indian, South Indian,",
        location: "Prasia Road",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/hxxasn2kf8g9eyi9eonq",
    },

]